version: "3.7"

services:
  service: &service
    # build:
    #   dockerfile: ./docker/service.dockerfile
    #   context: .
    #   target: prod
    #   args:
    #     app_env: prod
    image: stephanlensky/hyacinth-prod:main
    stop_grace_period: "2s"
    volumes:
      - ./:/app
    links:
      - db
      - browserless
    depends_on:
      - db
      - browserless

  db:
    image: postgres
    env_file:
      - ".env"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: "unless-stopped"

  browserless:
    image: browserless/chrome
    environment:
      - MAX_CONCURRENT_SESSIONS=10
      - CONNECTION_TIMEOUT=3600000 # 60 minute timeout
    ports:
      - "3000:3000"

  devbox: &devbox
    <<: *service
    # build:
    #   dockerfile: ./docker/service.dockerfile
    #   context: .
    #   target: dev
    #   args:
    #     app_env: dev
    image: stephanlensky/hyacinth-dev:main
    entrypoint: "poetry shell"
    stdin_open: true
    tty: true

  test:
    <<: *devbox
    command: ["just", "test"]

  pgweb:
    image: sosedoff/pgweb
    env_file:
      - ".env"
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/postgres?sslmode=disable
    restart: "unless-stopped"
    ports:
      - "8081:8081"
    links:
      - db
    depends_on:
      - db

volumes:
  pgdata:
