version: "3.7"

services:
  service: &service
    env_file:
      - ".env"
    build:
      dockerfile: ./docker/service.dockerfile
      context: .
      target: prod
      args:
        app_env: prod
    stop_grace_period: "2s"
    volumes:
      - ./:/app
    links:
      - db
      - redis
    depends_on:
      - db
      - redis

  db:
    image: postgres
    env_file:
      - ".env"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: "unless-stopped"

  redis:
    image: "redis:7.0.12"
    env_file:
      - ".env"
    restart: "unless-stopped"
    stop_grace_period: "2s"
    volumes:
      - redis:/data

  devbox: &devbox
    <<: *service
    build:
      dockerfile: ./docker/service.dockerfile
      context: .
      target: dev
      args:
        app_env: dev
    entrypoint: /bin/bash
    stdin_open: true
    tty: true

  test:
    <<: *devbox
    command: ["/bin/sh", "docker/scripts/test-docker-entrypoint.sh"]

  migrations:
    <<: *service
    depends_on:
      - db
    command: ["/bin/sh", "docker/scripts/migrations-docker-entrypoint.sh"]

  pgweb:
    image: sosedoff/pgweb
    env_file:
      - ".env"
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/postgres?sslmode=disable
    restart: "unless-stopped"
    ports:
      - "8081:8081"
    links:
      - db
    depends_on:
      - db

volumes:
  redis:
  pgdata:
